version: "1.1"

services:
  backend:
    env_file: .env
    build: .
    tty: true
    command:
      - --host=0.0.0.0
      - --port=80
      - --reload
      - --reload-dir=/DirectWave/src
      - --log-level=warning
    ports:
      - "80:80"
    volumes:
      - ./src:/DirectWave/src
      - ./resources:/DirectWave/resources
      - ./files:/DirectWave/files
#      - /media:/DirectWave/media

  database:
    env_file: .env
    image: postgres:15.1-alpine
    expose:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
  files: